model_name: "tiny_LLaMA_1b"
name: "tiny_LLaMA_1b"

# Training Config
per_node_batch_size: 256
learning_rate: 0.0004
min_lr: 0.00004
per_gpu_batch_size: 4
max_step: 16000
use_activation_checkpoint: False 
lr_schedule: "cosine"
# Logging 
log_step_interval: 2
 

# Fixed Hyperparam
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0
warmup_steps: 200
num_of_devices: 8

# Data
train_data_dir:  data/SP_tokenized
val_data_dir: data/SP_tokenized
train_data_config:
  - - "train_slim"
    - 1.0
val_data_config:
  - - "validation"
    - 1.0
seed: 3407

# Resume
resume: false
pretrained_path: None